=== mgeebs/WebAPI-HW0/movies_actors_db.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="movie"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="movie">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="year"/>
                <xs:element ref="genre"/>
                <xs:element ref="actors"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title">
            <xs:simpleType>
                <xs:restriction base="xs:normalizedString">
                    <xs:minLength value="1"/>
                </xs:restriction>
            </xs:simpleType>
    </xs:element>
    <xs:element name="year">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="4"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="genre">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="Action"/>
                <xs:enumeration value="Adventure"/>
                <xs:enumeration value="Comedy"/>
                <xs:enumeration value="Drama"/>
                <xs:enumeration value="Fantasy"/>
                <xs:enumeration value="Horror"/>
                <xs:enumeration value="Mystery"/>
                <xs:enumeration value="Thriller"/>
                <xs:enumeration value="Western"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="actors">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="actor"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="actor">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="birthdate"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="name">
        <xs:simpleType>
            <xs:restriction base="xs:normalizedString">
                    <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="birthdate" type="xs:date"/>
</xs:schema>

=== mgeebs/WebAPI-HW0/movies_actors_db.xml
<?xml version="1.0"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://"
        xsi:schemaLocation="http:// http://movies_actors_db.xsd">
    <movie>
        <title>The Goonies</title>
        <year>1985</year>
        <genre>Adventure</genre>
        <actors>
            <actor>
                <name>Sean Astin</name>
                <birthdate>1971-02-25</birthdate>
            </actor>
            <actor>
                <name>Jeff Cohen</name>
                <birthdate>1974-06-25</birthdate>
            </actor>
            <actor>
                <name>Corey Feldman</name>
                <birthdate>1972-07-16</birthdate>
            </actor>
        </actors>
    </movie>
    <movie>
        <title>Back to the Future</title>
        <year>1985</year>
        <genre>Adventure</genre>
        <actors>
            <actor>
                <name>Michael J. Fox</name>
                <birthdate>1961-06-09</birthdate>
            </actor>
            <actor>
                <name>Christopher Lloyd</name>
                <birthdate>1938-10-22</birthdate>
            </actor>
        </actors>
    </movie>
</movies>
